name: Docker compose actions workflow
on:
  push:
      branches: [master]

jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build the Docker image
        run: docker compose -f docker-compose.yml build
      - name: Check files
        run: ls 
      - run: docker build -t dianaioanaenoiu/multi-client ./client
      - run: docker build -t dianaioanaenoiu/multi-nginx ./nginx
      - run: docker build -t dianaioanaenoiu/multi-server ./server
      - run: docker build -t dianaioanaenoiu/multi-worker ./worker
      - run: docker push dianaioanaenoiu/multi-client 
      - run: docker push dianaioanaenoiu/multi-nginx 
      - run: docker push dianaioanaenoiu/multi-server 
      - run: docker push dianaioanaenoiu/multi-worker 

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: multi-docker
          environment_name: Multidocker-env-1
          existing_bucket_name: elasticbeanstalk-eu-west-2-735504675342
          region: eu-west-2
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip


 