name: Docker compose actions workflow
on:
  push:
      branches: [master]

jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker compose -f docker-compose.yml build
      - name: Check files
        run: ls 
    
      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*' 'node_modules'
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: multi-docker
          environment_name: Multidocker-env
          existing_bucket_name: elasticbeanstalk-eu-west-2-735504675342
          region: eu-west-2
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip

 